### PR TITLE
Lots of Puppet 5 facter additions

### PR DESCRIPTION
**Pull request by treydock**
Add Puppet 5 to RedHat and Debian based fact collection.
Fix OS detection to handle both EL6 and EL7.
Lots of fact additions for Facter 3.9, 3.10 and 3.11

### CODE REVIEW

**Comment by Dan33l** [comment]
Hi,

It looks that tests are failing due to hugo theme:
```
fatal: clone of 'git@github.com:camptocamp/hugo-elate-theme.git' into submodule path '/home/travis/build/camptocamp/facterdb/hugo/themes/elate' failed
Failed to clone 'hugo/themes/elate' a second time, aborting
```
Some camptocamp admins (@mcanevet @raphink ) can have a look ? 
I am interested to have the PR merged.

**Comment by raphink** [comment]
This was fixed in https://github.com/camptocamp/facterdb/commit/582b765c9e9fa969708a8b75aeaad4d8d3b18bd2, so a rebase should be sufficient

**Comment by Dan33l** [comment]
Thank you @raphink.

Since it is hard to maintain manually and without error the array `Facter version and Operating System coverage` in `README.md`, can we consider to remove it from the file ? The conflict is from this big array. And it does not look obvious to avoid mistakes to solve conflict.

**Comment by raphink** [comment]
It shouldn't be hard to maintain the table, as there is a `rake table` command provided to regenerate it.

**Comment by Dan33l** [comment]
This should be probably closed since #95 is merged.

**Comment by raphink** [comment]
Fixed in #95

**Pull request closed without merging**
