### PR TITLE
Create facter 2.5 files to support the release of facter 2.5

### PR DESCRIPTION
**Pull request by cyberious**
- Copied files from 2.4 and modified puppetversion to 4.10.2 and facterversion to 2.5.0

### CODE REVIEW

**Comment by cyberious** [comment]
errors look unrelated to my PR

**Comment by mcanevet** [comment]
@cyberious I'd prefer not not copy/paste/modify facts, but generate it from scratch with real version of Puppet Agent using the scripts provided

**Comment by baurmatt** [comment]
This is definitely needed as rspec tests seem to be broken for Facter 2.5.0 and Windows facts.

**Comment by SimonHoenscheid** [comment]
We should think about replacing facterdb. we patched it before. 
camptocamp gave a lot of the projects to the community, because AFAIK, they are no longer using puppet. could be also a solution to give facterdb to voxpopuli to maintain it.

**Comment by cdenneen** [comment]
Until this can be done as desired can someone update the gemspec to <2.5.0 of facter?

**Comment by cyberious** [comment]
https://github.com/mcanevet/rspec-puppet-facts/pull/53 have a fix for rspec-puppet-facts if relevant

**Comment by vladgh** [comment]
Any update on this?

**Comment by rodjek** [comment]
I've generated 2.5 fact sets for many of the operating systems in #46

**Comment by DavidS** [comment]
Fixed in #46

**Pull request closed without merging**
