### PR TITLE
(maint) Add `rake table` task + update README.md + better Windows detection

### PR DESCRIPTION
**Pull request by glennsarti**
Before this patch, it wasn't clear which versions of each OS had data
for any given version of facter.

This patch addresses that problem by adding a **Facter version and
Operating System coverage** table to the `README.md`.  The markdown for
the table can be maintained using the new rake task, `rake table`.

Glenn Sarti: This commit is based on the work by op-ct

---

Previously the fact information was not enough to determine the Windows version.
This is due to deficiencies in the facter facts not so much this gem.  This
commit adds a helper into the fact reading to record the filename used to load
the factsets. This is then used as a hint when generating the README table.
This is enabled using an environment variable, and is off by default.  This is
because these facts would not exist in a normal factset for a system of that
type.

### CODE REVIEW

**Comment by glennsarti** [comment]
Not sure why travis is failing.  Can't read the logs

**Comment by glennsarti** [comment]
Hrmm...Something screwy with Travis.

**Comment by mcanevet** [comment]
I think this PR is safe. What do you think @DavidS @rodjek ?

**Comment by DavidS** [comment]
Nice!

The travis failures seem to be connected to the hugo thing.

**Pull request merged**
