### PR TITLE
(#77)(#78)  Add default factset tests and fix failures

### PR DESCRIPTION
**Pull request by glennsarti**
Previously there were many default fact files which are just duplicates.  This
PR adds a test will performs a simple file hash comparison of all default
factset files and fails and displays any duplicate factsets.

---

Previously many factset files were in the wrong directory which made maintenance
and debugging difficult.  This PR adds tests to ensure that the factset
files are indeed JSON parsable and that the facter version in the file matches
the directory it is located in.

### CODE REVIEW

**Comment by glennsarti** [comment]
Note this PR supercedes https://github.com/camptocamp/facterdb/pull/54

**Comment by glennsarti** [comment]
@DavidS I've added your revert here

**Comment by glennsarti** [comment]
Also added the submodule ref fix to help Travis.

**Comment by DavidS** [comment]
Needs the constants in the number_of_files tests fixed up though. :man_shrugging:

**Comment by glennsarti** [comment]
Still Work in Progress.  Fixing the broken tests

**Pull request merged**
