### PR TITLE
Prepare release 0.8.3

### PR DESCRIPTION
**Pull request by Phil0xF7**
Our CI tests are failing on version 0.8.2 because of missing facts so we'd like to get a new release with the new changes if possible.

### CODE REVIEW

**Comment by bovy89** [comment]
+1

**Comment by bastelfreak** [comment]
Any objections on a 1.0.0 release?

**Comment by Phil0xF7** [comment]
@bastelfreak No objections from me :)

**Comment by bastelfreak** [comment]
This PR is obsolete since https://github.com/camptocamp/facterdb/pull/134

**Pull request closed without merging**
