### PR TITLE
Add CentOS 8 facts

### PR DESCRIPTION
**Pull request by traylenator**
Facts for CentOS 8 have been added.

In addition the method for determing Redhat/CentOS/Fedora
family and osversion has been altered to use
```
rpm -qf /etc/redhat-release --qf '%{name}
rpm -qf /etc/redhat-release --qf %{version}'
```
output.

After automatic generation the ec2_metadata fact was massaged to
remove some local information. ip, usernames and mac address.

### CODE REVIEW

**Comment by traylenator** [comment]
I think I cheated with something.

While the facts were created inside vagrant okay I was unsure how the facts were meant to get back out of the guest?

In the end I took them out using vagrant's 'rsync-back` plugin but I'm not sure that was good.  Vagrant virgin.

The other error of notice was the macaddress fact failing due to a lack of host being installed.

**Comment by traylenator** [comment]
Tests fail in master as well (for me)  - next week.

**Comment by bastelfreak** [comment]
@raphink @mcanevet can you please have a look and merge and release? Are you interested in migrating this to Vox Pupuli (or granting more people commit access)?

**Comment by raphink** [comment]
Great

**Pull request merged**
