### PR TITLE
Add missing facts for Fedora 20, 21, and 26

### PR DESCRIPTION
**Pull request by blackknight36**
Added fact files for Fedora 20, 21, and 26 to the facter 2.4 database.

### CODE REVIEW

**Comment by DavidS** [comment]
Thank you very much for your contribution!

**Comment by blackknight36** [comment]
No problem.  I have noticed a slight issue on modules that only have Fedora 20 listed as a supported OS.  For example, rspec will show an error like this.

> No facts were found in the FacterDB for: [{:facterversion=>"/\\A2\\.4\\./", :operatingsystem=>"Fedora", :operatingsystemrelease=>"/^20/", :hardwaremodel=>"x86_64"}]

**Comment by DavidS** [comment]
@blackknight36 yeah, there seems to be something wrong with the facts you collected. https://github.com/camptocamp/facterdb/pull/50/files#diff-3f46c0bba56680b5787d4de77b8a8d98R16 shows `"facterversion": "1.7.6"` in the `facts/2.4/fedora-20-x86_64.facts` file. That's not right.

**Comment by blackknight36** [comment]
@DavidS It looks like the node itself has an older version of facter than the system I'm running tests on.

> [root@node ~]# facter --version
1.7.6

Changing the facterversion fact to "2.4.1" does allow tests to run under Fedora 20 as shown below.

>ipmi
  on fedora-20-x86_64
    should contain Package[OpenIPMI] with ensure => "installed"
    should contain Package[ipmiutil] with ensure => "installed"
    should contain Package[ipmitool] with ensure => "installed"
    should contain File[ipmi_conf] that requires Package[OpenIPMI], Package[ipmiutil] and Package[ipmitool]
  on centos-7-x86_64
    should contain Package[OpenIPMI] with ensure => "installed"
    should contain Package[ipmiutil] with ensure => "installed"
    should contain Package[ipmitool] with ensure => "installed"
    should contain File[ipmi_conf] that requires Package[OpenIPMI], Package[ipmiutil] and Package[ipmitool]

I can submit another PR to fix this if you want.

**Comment by DavidS** [comment]
The point of the facterdb is to collect the actual facts from a specific facter version on a specific OS. Just changing the facterversion in the json is not sufficient, since different facter versions have different sets of facts, and would make tests of other modules based on those facts invalid. Even for your own use-case, testing against 2.4 facts is pretty useless, if the code will run against 1.7.6 in production.

**Comment by DavidS** [comment]
I've opened https://github.com/camptocamp/facterdb/pull/54 to rectify the bigger issue of wrong data.

**Pull request merged**
