### PR TITLE
Install redhat-lsb-core to provide additional facts

### PR DESCRIPTION
**Pull request by dhoppe**
We already install ```lsb-core``` at Debian related operating systems. We should also install ```redhat-lsb-core``` at RedHat related operating systems. 

This will provide additional facts like:
```
...
+    "distro": {
+      "codename": "Final",
+      "description": "CentOS release 6.10 (Final)",
+      "id": "CentOS",
+      "release": {
+        "full": "6.10",
+        "major": "6",
+        "minor": "10"
+      },
+      "specification": ":base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch"
+    },
```

### CODE REVIEW

**Comment by mcanevet** [comment]
@dhoppe I intentionally didn't install extra packages that provides additional facts so that this project works on a vanilla installation (add specially had in mind the `lsb_*` facts that are not available by default on Red Hat).
I'm opened to discussion, but for now I'm against merging this.
@rodjek @DavidS what do you think?

**Comment by dhoppe** [comment]
Puppet modules often use the codename of a release and I want to get rid of constructs like this:
* https://github.com/voxpupuli/puppet-fail2ban/blob/master/spec/classes/init_spec.rb#L10-L26

**Comment by bastelfreak** [comment]
Since so many modules, even Puppetlabs modules, depend on those facts I would like to see a dependency from facter to the lsb packages .

**Comment by mcanevet** [comment]
Indeed, but isn't this for historical reasons that should be avoid?

**Comment by ekohl** [comment]
I think https://github.com/camptocamp/facterdb/pull/138#issuecomment-562543728 is still correct. :-1: on installing them. People should not count on them being present because there are many systems where they simply aren't available. The example in fail2ban is IMHO bad module design and not something facterdb should cater for.

**Comment by raphink** [comment]
Agreed @ekohl and @mcanevet. Especially when it comes to testing, we should rely on a bare minimal environment, to ensure passing tests won't result in broken production.

**Pull request closed without merging**
