### PR TITLE
Adding facts from Solaris 11 x86 & SPARC

### PR DESCRIPTION
**Pull request by genebean**
The facts were generated on hosts with facter 3.11.11 and 3.14.7.

### CODE REVIEW

**Comment by genebean** [comment]
FWIW, I think the rake task is improperly naming the Solaris entries in the readme table

**Comment by bastelfreak** [comment]
Hi @genebean, thanks for the awesome PR! Could you please update the hostname to `foo` and the domain to `example.com` in the fact sets? That's what we usually set. Also I'm wondering why they appear as solaris 1/2 in the readme. the script should pick up the major version number. I had no time yet to take a look at it.

**Comment by genebean** [comment]
I can absolutely update those but it’ll be tomorrow.

**Comment by genebean** [comment]
All done @bastelfreak

**Comment by bastelfreak** [comment]
Can one of the admins here look into this? :)

**Pull request merged**
